version: "3"

services:

  nuxtapp:
    container_name: nuxtapp
    build: ./nuxtapp
    ports:
      - 8082:3000
    # volumes:
    #   - ./nuxtapp:/home/app
    env_file:
      - ./nuxtapp/.env
    depends_on:
      # - redis
      - pg
      - flaskapi
  
  flaskapi:
    container_name: flaskapi
    build: ./flaskapi
    restart: always
    ports:
      - 8081:5000
    # volumes:
    #   - ./flaskapi:/home/app
    depends_on:
      - pg
      # - redis
    env_file:
      - ./flaskapi/.env

  pg:
    container_name: pg
    image: postgres:14.5
    restart: always
    ports:
      - 5544:5432
    env_file:
      - ./db/.env
    volumes:
      - vol_pg:/var/lib/postgresql/
    # depends_on:
    #   - redis

  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - 6879:6379
  #   restart: always
  #   volumes:
  #     - ./api/redis.conf:/etc/redis/redis.conf
  #   command: ["redis-server", "/etc/redis/redis.conf"]

volumes:
  vol_pg:
