
###
http://localhost:3001/app/122--nuxtapp/api/status

###

POST http://199.247.16.115:8081/a
Accept: application/json
Content-Type: application/json

{
  "value": "@122333"
}

###

http://199.247.16.115:8081/a
Accept: application/json

###

http://199.247.16.115:8081/docs/@vars
Accept: application/json

###

POST http://199.247.16.115:8081/docs/@vars
Accept: application/json
Content-Type: application/json

{
  "data": {
    "app:version": "0.0.0.0"
  }
}

###

DELETE http://199.247.16.115:8081/docs/@vars
Accept: application/json
Content-Type: application/json

{
  "id": 122
}

###
